### ISSUE TITLE
error adding addon

### ISSUE THREAD

**Issue by LeeAdo** [CruzR/Blender-MDL#14] opened 2013-07-27 14:20 UTC
I get the following errors when I try to enable addin on blender 2.68

![error](https://f.cloud.github.com/assets/5102742/866972/a7248642-f6c7-11e2-860b-11bd3951626f.PNG)

**Comment by CruzR** [comment] 2013-07-29 06:26
Why did you close this issue? Were you able to resolve it?

**Comment by CruzR** [comment] 2013-07-29 21:22
I can't reproduce this; enabling the addon works fine for me on Blender 2.68.

Could you provide a bit more information? And could you please upload your copy of the script to some file host so I can diff it against the original? Maybe your browser / OS / whatever messed up the download.

**Comment by LeeAdo** [comment] 2013-07-30 11:07
please find attached the file that I downloaded from github.  I am using win7 and blender 2.68

thanks for your help.

I opened the file and copy and pasted into notepad and saved the file to my local drive.

Lee A.

Date: Mon, 29 Jul 2013 14:22:47 -0700

**Comment by LeeAdo** [comment] 2013-07-30 18:34
I figured it out.   notepad took all the formatting out of it.   I needed to click on raw and do a save as.  that worked.  sorry to waist your time on user error, and thanks for the plugin.

From: laadolfson@hotmail.com
To: reply@reply.github.com
Subject: RE: [Blender-MDL] error adding addon (#14)
Date: Tue, 30 Jul 2013 06:07:44 -0500

please find attached the file that I downloaded from github.  I am using win7 and blender 2.68

thanks for your help.

I opened the file and copy and pasted into notepad and saved the file to my local drive.

Lee A.

Date: Mon, 29 Jul 2013 14:22:47 -0700

**Comment by CruzR** [comment] 2013-07-31 16:37
Alright, I'll close this issue.

**Closed as completed by CruzR** 2013-07-31 16:37 UTC
